# Generated by Django 5.0.6 on 2024-06-05 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biodata',
            old_name='msg',
            new_name='message',
        ),
    ]
