# Generated by Django 5.0.6 on 2024-06-05 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_msg_biodata_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BioData',
        ),
    ]
